<?php
namespace App\Services;use App\Models\Applicant;
final class NotificationTemplateService { private const DEFAULTS=[
'registration_created'=>"Assalamu'alaikum {full_name},\n\nPendaftaran Anda berhasil diterima dengan nomor {registration_number}. Simpan nomor tersebut untuk mengecek status pendaftaran.\n\nStatus pembayaran saat ini: {payment_status_label}. Silakan selesaikan pembayaran sesuai petunjuk pada halaman pendaftaran.",
'payment_unpaid'=>"Assalamu'alaikum {full_name},\n\nPembayaran untuk pendaftaran {registration_number} belum dilakukan. Silakan lanjutkan pembayaran sebelum batas waktu agar proses pendaftaran dapat diteruskan.",
'payment_pending'=>"Assalamu'alaikum {full_name},\n\nPembayaran pendaftaran {registration_number} sedang menunggu konfirmasi. Kami akan memberitahukan kembali setelah pembayaran berhasil diverifikasi.",
'payment_paid'=>"Alhamdulillah, pembayaran pendaftaran {registration_number} atas nama {full_name} telah berhasil dan terverifikasi. Anda dapat melanjutkan proses berikutnya.",
'payment_failed'=>"Assalamu'alaikum {full_name},\n\nPembayaran pendaftaran {registration_number} tidak berhasil atau dibatalkan. Silakan lakukan pembayaran kembali atau hubungi panitia jika dana telah terpotong.",
'payment_expired'=>"Masa berlaku pembayaran pendaftaran {registration_number} telah berakhir. Silakan membuat transaksi pembayaran baru.",
'payment_refunded'=>"Dana pembayaran pendaftaran {registration_number} telah dikembalikan. Hubungi panitia jika Anda membutuhkan informasi lebih lanjut.",
'document_pending_review'=>"Dokumen pendaftaran {registration_number} telah diterima dan sedang diperiksa oleh panitia.",
'document_revision_submitted'=>"Dokumen perbaikan untuk {registration_number} telah diterima dan akan diperiksa kembali.",
'document_incomplete'=>"Dokumen pendaftaran {registration_number} memerlukan perbaikan. Silakan cek status pendaftaran untuk melihat catatan panitia dan unggah dokumen yang sesuai.",
'document_complete'=>"Alhamdulillah, seluruh dokumen pendaftaran {registration_number} telah dinyatakan lengkap.",
'selection_not_scheduled'=>"Status seleksi {registration_number} diperbarui: belum dijadwalkan. Pantau informasi berikutnya melalui halaman cek status.",
'selection_scheduled'=>"Pendaftaran {registration_number} telah masuk jadwal seleksi. Silakan buka halaman cek status untuk melihat informasi selengkapnya.",
'selection_attending_test'=>"Status seleksi {registration_number} diperbarui: sedang mengikuti proses seleksi.",
'selection_passed'=>"Selamat {full_name}! Anda dinyatakan DITERIMA pada PMB Pendidikan Kader Ulama. Nomor pendaftaran: {registration_number}. Silakan ikuti arahan lanjutan dari panitia.",
'selection_not_passed'=>"Terima kasih {full_name} telah mengikuti seluruh proses. Berdasarkan hasil seleksi, pendaftaran {registration_number} belum dinyatakan diterima.",
'selection_withdrawn'=>"Pendaftaran {registration_number} telah dibatalkan atau mengundurkan diri. Hubungi panitia apabila status ini tidak sesuai.",
];public function __construct(private SettingsService $settings){}public function all():array{return collect(self::DEFAULTS)->mapWithKeys(fn($v,$k)=>[$k=>$this->settings->get('notifications.'.$k,$v)])->all();}public function render(string $event,Applicant $a,?string $fallback=null):string{$template=$this->settings->get('notifications.'.$event,self::DEFAULTS[$event]??$fallback??"Assalamu'alaikum {full_name},\n\nTerdapat pembaruan status PMB untuk {registration_number}. Silakan cek status pendaftaran Anda.");return strtr($template,['{registration_number}'=>$a->registration_number,'{full_name}'=>$a->full_name,'{payment_status}'=>$a->payment_status->value,'{document_status}'=>$a->document_status->value,'{selection_status}'=>$a->selection_status->value,'{payment_status_label}'=>$this->label($a->payment_status->value),'{document_status_label}'=>$this->label($a->document_status->value),'{selection_status_label}'=>$this->label($a->selection_status->value)]);}private function label(string $value):string{return ['unpaid'=>'Belum dibayar','pending'=>'Menunggu konfirmasi','paid'=>'Lunas','failed'=>'Gagal','expired'=>'Kedaluwarsa','refunded'=>'Dikembalikan','pending_review'=>'Menunggu pemeriksaan','revision_submitted'=>'Perbaikan dikirim','incomplete'=>'Perlu perbaikan','complete'=>'Lengkap','not_scheduled'=>'Belum dijadwalkan','scheduled'=>'Dijadwalkan','attending_test'=>'Mengikuti seleksi','passed'=>'Diterima','not_passed'=>'Tidak diterima','withdrawn'=>'Dibatalkan'][$value]??str_replace('_',' ',$value);}}
