<?php
namespace Tests\Feature;
use App\Jobs\SendApplicantNotification;
use App\Actions\QueueApplicantNotification;
use App\Models\{AdmissionPeriod,Applicant,NotificationLog};
use App\Services\Duitku\DuitkuClient;
use App\Services\Tripay\TripayClient;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\{Http,Queue};
use App\Services\SettingsService;
use Tests\TestCase;
class ProviderIntegrationTest extends TestCase {
 use RefreshDatabase;
 private function applicant():Applicant{$p=AdmissionPeriod::create(['name'=>'Aktif','year'=>2026,'registration_prefix'=>'PKU','starts_at'=>now(),'ends_at'=>now()->addDay(),'registration_fee'=>250000,'is_active'=>true]);return Applicant::create(['admission_period_id'=>$p->id,'registration_number'=>'PKU-2026-000555','submission_uuid'=>fake()->uuid(),'full_name'=>'Provider Test','birth_place'=>'Bogor','birth_date'=>'2000-01-01','address'=>'Alamat','whatsapp_normalized'=>'6281234567890','whatsapp_display'=>'0812','email'=>'provider@example.test','payment_status'=>'unpaid','document_status'=>'pending_review','selection_status'=>'not_scheduled','consented_at'=>now(),'submitted_at'=>now()]);}
 public function test_duitku_create_payload_and_signature():void{$a=$this->applicant();config(['services.duitku.mode'=>'sandbox','services.duitku.api_key'=>'secret','services.duitku.merchant_code'=>'D123']);Http::fake(['api-sandbox.duitku.com/*'=>Http::response(['merchantCode'=>'D123','reference'=>'REF1','statusCode'=>'00','statusMessage'=>'SUCCESS','paymentUrl'=>'https://app-sandbox.duitku.com/redirect_checkout?reference=REF1'],200)]);$data=app(DuitkuClient::class)->create($a,'POP','INV1',250000);$this->assertSame('REF1',$data['reference']);Http::assertSent(function($r){$timestamp=$r->header('x-duitku-timestamp')[0]??'';return $r->url()==='https://api-sandbox.duitku.com/api/merchant/createInvoice'&&!isset($r['merchantCode'])&&!isset($r['signature'])&&!isset($r['paymentMethod'])&&$r['merchantOrderId']==='INV1'&&$r['phoneNumber']==='081234567890'&&$r['itemDetails'][0]['price']===250000&&$r['additionalParam']==='registration_number=PKU-2026-000555'&&$r['merchantUserInfo']==='PKU-2026-000555'&&$r['callbackUrl']===route('webhooks.duitku')&&$r['returnUrl']===route('registration.success','PKU-2026-000555')&&$r->hasHeader('x-duitku-merchantcode','D123')&&$r->hasHeader('x-duitku-signature',hash_hmac('sha256','D123'.$timestamp,'secret'));});}
 public function test_duitku_payment_endpoint_uses_inertia_external_location():void{$a=$this->applicant();config(['services.duitku.mode'=>'sandbox','services.duitku.api_key'=>'secret','services.duitku.merchant_code'=>'D123']);Http::fake(['api-sandbox.duitku.com/*'=>Http::response(['merchantCode'=>'D123','reference'=>'REF2','statusCode'=>'00','paymentUrl'=>'https://app-sandbox.duitku.com/redirect_checkout?reference=REF2'],200)]);$this->withHeader('X-Inertia','true')->post(route('payment.create',$a->registration_number),['method'=>'POP'])->assertStatus(409)->assertHeader('X-Inertia-Location','https://app-sandbox.duitku.com/redirect_checkout?reference=REF2');$this->assertDatabaseHas('payments',['applicant_id'=>$a->id,'provider'=>'duitku','provider_reference'=>'REF2','checkout_url'=>'https://app-sandbox.duitku.com/redirect_checkout?reference=REF2']);}
 public function test_duitku_rejection_message_is_visible_without_exposing_credentials():void{$a=$this->applicant();config(['services.duitku.mode'=>'sandbox','services.duitku.api_key'=>'secret-value','services.duitku.merchant_code'=>'D123']);Http::fake(['api-sandbox.duitku.com/*'=>Http::response(['statusCode'=>'01','statusMessage'=>'Payment method tidak aktif'],400)]);$this->from(route('payment.show',$a->registration_number))->post(route('payment.create',$a->registration_number),['method'=>'OV'])->assertRedirect(route('payment.show',$a->registration_number))->assertSessionHasErrors(['method'=>'Duitku: Payment method tidak aktif']);$this->assertDatabaseCount('payments',0);}
 public function test_tripay_create_payload_and_signature():void{$a=$this->applicant();config(['services.tripay.mode'=>'sandbox','services.tripay.api_key'=>'api-secret','services.tripay.private_key'=>'private-secret','services.tripay.merchant_code'=>'T123']);Http::fake(['tripay.co.id/api-sandbox/transaction/create'=>Http::response(['success'=>true,'data'=>['reference'=>'TRIPAY-REF','merchant_ref'=>'INV2','amount'=>250000,'checkout_url'=>'https://tripay.co.id/checkout/TRIPAY-REF']],200)]);$data=app(TripayClient::class)->create($a,'BRIVA','INV2',250000);$this->assertSame('TRIPAY-REF',$data['reference']);Http::assertSent(fn($r)=>$r->hasHeader('Authorization','Bearer api-secret')&&$r['merchant_ref']==='INV2'&&$r['signature']===hash_hmac('sha256','T123INV2250000','private-secret'));}
 public function test_tripay_channels_only_require_api_key_and_map_customer_fee():void{config(['services.tripay.mode'=>'sandbox','services.tripay.api_key'=>'api-secret','services.tripay.private_key'=>null,'services.tripay.merchant_code'=>null]);Http::fake(['tripay.co.id/api-sandbox/merchant/payment-channel'=>Http::response(['success'=>true,'data'=>[['group'=>'Virtual Account','code'=>'BRIVA','name'=>'BRI Virtual Account','active'=>true,'minimum_amount'=>10000,'maximum_amount'=>10000000,'fee_customer'=>['flat'=>1000,'percent'=>1.0],'icon_url'=>'https://tripay.co.id/briva.png']]],200)]);$channels=app(TripayClient::class)->channels(10000);$this->assertSame('BRIVA',$channels[0]['code']);$this->assertSame(1100,$channels[0]['fee']);Http::assertSent(fn($r)=>$r->hasHeader('Authorization','Bearer api-secret'));}
 public function test_fonnte_job_uses_post_authorization_and_marks_sent():void{$a=$this->applicant();config(['services.fonnte.token'=>'token','services.fonnte.base_url'=>'https://api.fonnte.com','services.fonnte.country_code'=>'62']);Http::fake(['api.fonnte.com/send'=>Http::response(['status'=>true,'requestid'=>'REQ1'])]);$log=NotificationLog::create(['applicant_id'=>$a->id,'channel'=>'whatsapp','event_type'=>'test','recipient_masked'=>'6281****890','unique_key'=>'test:wa','status'=>'queued']);(new SendApplicantNotification($log->id,'Pesan tes'))->handle();Http::assertSent(fn($r)=>$r->method()==='POST'&&$r->hasHeader('Authorization','token')&&$r['target']==='6281234567890');$this->assertSame('sent',$log->fresh()->status);}
 public function test_disabled_whatsapp_channel_is_not_queued():void{$a=$this->applicant();Queue::fake();$settings=app(SettingsService::class);$settings->put('notifications','notifications.whatsapp_enabled',false,'boolean');$settings->put('notifications','notifications.email_enabled',true,'boolean');app(QueueApplicantNotification::class)->execute($a,'registration_created','Tes');$this->assertDatabaseHas('notification_logs',['applicant_id'=>$a->id,'channel'=>'email']);$this->assertDatabaseMissing('notification_logs',['applicant_id'=>$a->id,'channel'=>'whatsapp']);Queue::assertPushed(SendApplicantNotification::class,1);}
}
