<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void {
  Schema::table('users',function(Blueprint $t){$t->string('role')->default('viewer')->index();$t->boolean('is_active')->default(true);$t->boolean('must_change_password')->default(false);$t->timestamp('last_login_at')->nullable();});
  Schema::create('admission_periods',function(Blueprint $t){$t->id();$t->string('name');$t->unsignedSmallInteger('year');$t->string('registration_prefix',20);$t->dateTime('starts_at');$t->dateTime('ends_at');$t->unsignedInteger('quota')->nullable();$t->unsignedBigInteger('registration_fee');$t->boolean('is_active')->default(false)->index();$t->timestamps();});
  Schema::create('applicants',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignId('admission_period_id')->constrained()->restrictOnDelete();$t->string('registration_number',40);$t->string('submission_uuid',64);$t->string('full_name',150);$t->string('birth_place',100);$t->date('birth_date');$t->text('address');$t->string('whatsapp_normalized',20);$t->string('whatsapp_display',30);$t->string('email',190);$t->string('payment_status',30)->default('unpaid')->index();$t->string('document_status',30)->default('pending_review')->index();$t->string('selection_status',30)->default('not_scheduled')->index();$t->dateTime('consented_at');$t->dateTime('submitted_at');$t->dateTime('paid_at')->nullable();$t->dateTime('accepted_at')->nullable();$t->string('lookup_secret_hash')->nullable();$t->timestamps();$t->softDeletes();$t->unique(['admission_period_id','registration_number']);$t->unique(['admission_period_id','email']);$t->unique(['admission_period_id','whatsapp_normalized']);$t->unique(['admission_period_id','submission_uuid']);});
  Schema::create('applicant_documents',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('applicant_id')->constrained()->cascadeOnDelete();$t->string('type',40);$t->string('disk',30)->default('local');$t->string('path');$t->string('original_name');$t->string('mime_type',100);$t->string('extension',10);$t->unsignedBigInteger('size');$t->string('sha256',64);$t->unsignedSmallInteger('page_count')->nullable();$t->string('verification_status',30)->default('pending');$t->text('review_note')->nullable();$t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('reviewed_at')->nullable();$t->unsignedSmallInteger('version')->default(1);$t->timestamps();$t->softDeletes();$t->index(['applicant_id','type']);});
  Schema::create('payments',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('applicant_id')->constrained()->cascadeOnDelete();$t->string('provider',20);$t->string('merchant_ref')->unique();$t->string('provider_reference')->nullable()->unique();$t->string('payment_method',50)->nullable();$t->unsignedBigInteger('base_amount');$t->unsignedBigInteger('fee_merchant')->default(0);$t->unsignedBigInteger('fee_customer')->default(0);$t->unsignedBigInteger('total_amount');$t->string('status',30)->index();$t->text('checkout_url')->nullable();$t->json('instructions_json')->nullable();$t->timestamp('expires_at')->nullable();$t->timestamp('paid_at')->nullable();$t->timestamp('last_synced_at')->nullable();$t->json('request_payload_redacted')->nullable();$t->json('response_payload_redacted')->nullable();$t->timestamps();});
  Schema::create('payment_webhook_events',function(Blueprint $t){$t->id();$t->string('provider',20);$t->string('event_key')->unique();$t->string('provider_reference')->nullable();$t->string('event',40);$t->boolean('signature_valid');$t->json('payload_redacted')->nullable();$t->dateTime('received_at');$t->dateTime('processed_at')->nullable();$t->string('processing_status',30);$t->text('error')->nullable();$t->timestamps();});
  Schema::create('status_histories',function(Blueprint $t){$t->id();$t->foreignUlid('applicant_id')->constrained()->cascadeOnDelete();$t->string('dimension',30);$t->string('from_status',30)->nullable();$t->string('to_status',30);$t->text('note')->nullable();$t->nullableMorphs('changed_by');$t->timestamp('created_at')->useCurrent();});
  Schema::create('settings',function(Blueprint $t){$t->id();$t->string('group',40);$t->string('key')->unique();$t->longText('value')->nullable();$t->boolean('is_encrypted')->default(false);$t->string('type',20)->default('string');$t->timestamps();});
  Schema::create('notification_logs',function(Blueprint $t){$t->id();$t->foreignUlid('applicant_id')->nullable()->constrained()->nullOnDelete();$t->string('channel',20);$t->string('event_type',50);$t->string('recipient_masked');$t->string('unique_key')->unique();$t->string('provider_request_id')->nullable();$t->string('status',20)->index();$t->unsignedSmallInteger('attempts')->default(0);$t->text('last_error')->nullable();$t->timestamp('sent_at')->nullable();$t->timestamps();});
  Schema::create('otp_challenges',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('applicant_id')->constrained()->cascadeOnDelete();$t->string('purpose',30);$t->string('channel',20);$t->string('code_hash');$t->timestamp('expires_at')->index();$t->unsignedTinyInteger('attempts')->default(0);$t->timestamp('consumed_at')->nullable();$t->string('ip_hash',64);$t->timestamps();});
  Schema::create('audit_logs',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('action')->index();$t->nullableMorphs('auditable');$t->json('before_json')->nullable();$t->json('after_json')->nullable();$t->string('ip',64)->nullable();$t->text('user_agent')->nullable();$t->timestamp('created_at')->useCurrent();});
 }
 public function down():void { foreach(['audit_logs','otp_challenges','notification_logs','settings','status_histories','payment_webhook_events','payments','applicant_documents','applicants','admission_periods'] as $table) Schema::dropIfExists($table); Schema::table('users',fn(Blueprint $t)=>$t->dropColumn(['role','is_active','must_change_password','last_login_at'])); }
};
