<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;use App\Models\Applicant;use App\Support\IndonesianPhone;use Illuminate\Http\{RedirectResponse,Request};use Illuminate\Support\Facades\{DB,Storage};use Illuminate\Validation\Rule;use Inertia\{Inertia,Response};use Symfony\Component\HttpFoundation\BinaryFileResponse;use ZipArchive;
class ApplicantController extends Controller {
 public function index(Request $request):Response{$query=Applicant::query();if($search=$request->string('search')->trim()->toString())$query->where(fn($q)=>$q->where('registration_number','like',"%{$search}%")->orWhere('full_name','like',"%{$search}%"));foreach(['payment_status','document_status','selection_status'] as $field)if($request->filled($field))$query->where($field,$request->input($field));return Inertia::render('Admin/Applicants/Index',['applicants'=>$query->latest()->paginate(20)->withQueryString(),'filters'=>$request->only(['search','payment_status','document_status','selection_status'])]);}
 public function show(Applicant $applicant):Response{return Inertia::render('Admin/Applicants/Show',['applicant'=>$applicant->load('documents','payments')]);}
 public function edit(Applicant $applicant):Response{return Inertia::render('Admin/Applicants/Edit',['applicant'=>$applicant]);}
 public function update(Request $request,Applicant $applicant):RedirectResponse{$data=$request->validate(['full_name'=>['required','string','min:3','max:150'],'birth_place'=>['required','string','max:100'],'birth_date'=>['required','date','before_or_equal:today'],'address'=>['required','string','max:2000'],'email'=>['required','email','max:190',Rule::unique('applicants')->where('admission_period_id',$applicant->admission_period_id)->ignore($applicant->id)],'whatsapp'=>['required','string','max:30']]);$phone=IndonesianPhone::normalize($data['whatsapp']);if(Applicant::where('admission_period_id',$applicant->admission_period_id)->where('whatsapp_normalized',$phone)->where('id','!=',$applicant->id)->exists())return back()->withErrors(['whatsapp'=>'Nomor WhatsApp sudah digunakan pendaftar lain.']);$whatsapp=$data['whatsapp'];unset($data['whatsapp']);$applicant->update([...$data,'email'=>strtolower($data['email']),'whatsapp_normalized'=>$phone,'whatsapp_display'=>$whatsapp]);return redirect()->route('admin.applicants.show',$applicant)->with('success','Data pendaftar berhasil diperbarui.');}
 public function download(Applicant $applicant):BinaryFileResponse{abort_unless(class_exists(ZipArchive::class),503,'Ekstensi PHP ZIP belum aktif di server.');$applicant->load('documents');$path=tempnam(sys_get_temp_dir(),'pmb-applicant-');$zip=new ZipArchive();abort_unless($zip->open($path,ZipArchive::OVERWRITE)===true,500,'Arsip tidak dapat dibuat.');$summary="DATA PENDAFTAR PMB PKU\n\nNomor: {$applicant->registration_number}\nNama: {$applicant->full_name}\nEmail: {$applicant->email}\nWhatsApp: {$applicant->whatsapp_display}\nTempat/Tanggal Lahir: {$applicant->birth_place}, {$applicant->birth_date->format('d-m-Y')}\nAlamat: {$applicant->address}\nPembayaran: {$applicant->payment_status->value}\nBerkas: {$applicant->document_status->value}\nSeleksi: {$applicant->selection_status->value}\n";$zip->addFromString('data-pendaftar.txt',$summary);foreach($applicant->documents as $document)if(Storage::disk($document->disk)->exists($document->path)){$safeName=preg_replace('/[^A-Za-z0-9._-]/','_',basename($document->original_name));$zip->addFromString('dokumen/'.$document->type.'-'.$document->id.'-'.$safeName,Storage::disk($document->disk)->get($document->path));}$zip->close();return response()->download($path,$applicant->registration_number.'.zip')->deleteFileAfterSend(true);}
 public function destroy(Applicant $applicant):RedirectResponse{$applicant->load(['documents'=>fn($q)=>$q->withTrashed(),'payments']);foreach($applicant->documents as $document)Storage::disk($document->disk)->delete($document->path);DB::transaction(function()use($applicant){DB::table('notification_logs')->where('applicant_id',$applicant->id)->delete();DB::table('audit_logs')->where('auditable_type',Applicant::class)->where('auditable_id',$applicant->id)->delete();DB::table('payment_webhook_events')->whereIn('provider_reference',$applicant->payments->pluck('provider_reference')->filter())->delete();$applicant->forceDelete();});return redirect()->route('admin.applicants.index')->with('success','Pendaftar dan seluruh dokumennya telah dihapus permanen.');}
}
