<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Models\{AdmissionPeriod,Applicant,TestSession};
use Illuminate\Http\{RedirectResponse,Request};
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
use Inertia\{Inertia,Response};
class TestSessionController extends Controller {
 public function index():Response{return Inertia::render('Admin/TestSessions/Index',['sessions'=>TestSession::withCount('applicants')->with('applicants:id,registration_number,full_name,selection_status')->latest('starts_at')->get(),'periods'=>AdmissionPeriod::latest('year')->get(['id','name','is_active']),'eligible'=>Applicant::where('payment_status','paid')->where('document_status','complete')->whereIn('selection_status',['not_scheduled','scheduled'])->get(['id','registration_number','full_name'])]);}
 public function store(Request $request):RedirectResponse{$data=$request->validate(['admission_period_id'=>['required','exists:admission_periods,id'],'name'=>['required','string','max:150'],'starts_at'=>['required','date'],'ends_at'=>['nullable','date','after:starts_at'],'location'=>['nullable','string','max:255'],'maps_url'=>['nullable','url','max:1000'],'meeting_url'=>['nullable','url','max:1000'],'capacity'=>['nullable','integer','min:1','max:10000'],'instructions'=>['nullable','string','max:3000']]);TestSession::create($data);return back()->with('success','Sesi tes dibuat.');}
 public function assign(Request $request,TestSession $testSession):RedirectResponse{$data=$request->validate(['applicant_ids'=>['required','array','min:1'],'applicant_ids.*'=>['ulid','exists:applicants,id']]);DB::transaction(function()use($request,$testSession,$data){$applicants=Applicant::whereIn('id',$data['applicant_ids'])->lockForUpdate()->get();if($testSession->capacity&&$testSession->applicants()->count()+$applicants->count()>$testSession->capacity)throw ValidationException::withMessages(['applicant_ids'=>'Kapasitas sesi tidak mencukupi.']);foreach($applicants as $a){if($a->payment_status->value!=='paid'||$a->document_status->value!=='complete')throw ValidationException::withMessages(['applicant_ids'=>"{$a->registration_number} belum memenuhi syarat pembayaran dan berkas."]);$testSession->applicants()->syncWithoutDetaching([$a->id=>['attendance_status'=>'assigned','assigned_at'=>now(),'created_at'=>now(),'updated_at'=>now()]]);if($a->selection_status->value==='not_scheduled'){$a->update(['selection_status'=>'scheduled']);DB::table('status_histories')->insert(['applicant_id'=>$a->id,'dimension'=>'selection','from_status'=>'not_scheduled','to_status'=>'scheduled','note'=>'Dijadwalkan ke '.$testSession->name,'changed_by_type'=>'user','changed_by_id'=>$request->user()->id,'created_at'=>now()]);}}});return back()->with('success','Pendaftar berhasil dijadwalkan.');}
 public function result(Request $request,TestSession $testSession,Applicant $applicant):RedirectResponse{$data=$request->validate(['attendance_status'=>['required','in:assigned,attended,absent'],'score'=>['nullable','numeric','min:0','max:100'],'selection_status'=>['required','in:scheduled,attending_test,passed,not_passed'],'internal_note'=>['nullable','string','max:2000']]);abort_unless($testSession->applicants()->whereKey($applicant->id)->exists(),404);DB::transaction(function()use($request,$testSession,$applicant,$data){$testSession->applicants()->updateExistingPivot($applicant->id,['attendance_status'=>$data['attendance_status'],'score'=>$data['score']??null,'internal_note'=>$data['internal_note']??null,'attended_at'=>$data['attendance_status']==='attended'?now():null]);$before=$applicant->selection_status->value;if($before!==$data['selection_status']){$applicant->update(['selection_status'=>$data['selection_status'],'accepted_at'=>$data['selection_status']==='passed'?now():null]);DB::table('status_histories')->insert(['applicant_id'=>$applicant->id,'dimension'=>'selection','from_status'=>$before,'to_status'=>$data['selection_status'],'note'=>'Hasil sesi '.$testSession->name,'changed_by_type'=>'user','changed_by_id'=>$request->user()->id,'created_at'=>now()]);}});return back()->with('success','Hasil tes diperbarui.');}
}
