<?php

namespace App\Http\Controllers\Public;

use App\Models\AdmissionPeriod;
use App\Models\Applicant;
use App\Services\SettingsService;
use App\Support\IndonesianPhone;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\ValidationException;
use Inertia\Inertia;
use Inertia\Response;
use Symfony\Component\HttpFoundation\StreamedResponse;

class StatusLookupController
{
    public function index(Request $request): Response
    {
        return Inertia::render('Public/StatusLookup', [
            'initialIdentifier' => $request->string('identifier')->limit(190)->toString(),
        ]);
    }

    public function lookup(Request $request, SettingsService $settings): RedirectResponse
    {
        $data = $request->validate([
            'identifier' => ['required', 'string', 'max:190'],
        ], [
            'identifier.required' => 'Masukkan nomor pendaftaran, email, atau nomor HP/WhatsApp terdaftar.',
        ]);

        $identifier = trim($data['identifier']);
        $period = AdmissionPeriod::where('is_active', true)->first();
        $registrationNumber = strtoupper((string) preg_replace('/\s+/', '', $identifier));
        $applicant = Applicant::whereRaw('UPPER(registration_number) = ?', [$registrationNumber])->first();

        if (! $applicant && $period) {
            $year = (int) $settings->get('pmb.registration_year', $period->year);
            $query = Applicant::where('admission_period_id', $period->id)
                ->where('registration_number', 'like', $period->registration_prefix.'-'.$year.'-%');
            if (str_contains($identifier, '@')) {
                $applicant = $query->where('email', strtolower($identifier))->first();
            } else {
                try {
                    $phone = IndonesianPhone::normalize($identifier);
                    $applicant = $query->where('whatsapp_normalized', $phone)->first();
                } catch (\InvalidArgumentException) {
                    $applicant = null;
                }
            }
        }

        if (! $applicant) {
            throw ValidationException::withMessages([
                'identifier' => 'Nomor pendaftaran, email, atau nomor HP tidak ditemukan.',
            ]);
        }

        $request->session()->put('status_applicant_id', $applicant->id);

        return redirect()->route('status.show');
    }

    public function emailAccess(Request $request, Applicant $applicant): RedirectResponse
    {
        // The signed email URL proves that the visitor received a notification
        // generated by this application. Store the same short-lived session
        // access used by the regular lookup, then open the detail directly.
        $request->session()->put('status_applicant_id', $applicant->id);

        return redirect()->route('status.show');
    }

    public function show(Request $request): Response
    {
        $id = $request->session()->get('status_applicant_id');
        abort_unless($id, 403);
        $applicant = Applicant::with([
            'documents:id,applicant_id,type,original_name,verification_status,review_note,created_at',
            'payments:id,applicant_id,status,checkout_url,base_amount,fee_customer,total_amount,expires_at,created_at',
        ])->findOrFail($id);

        return Inertia::render('Public/StatusDetail', ['applicant' => [
            'id' => $applicant->id,
            'registration_number' => $applicant->registration_number,
            'full_name' => $applicant->full_name,
            'birth_place' => $applicant->birth_place,
            'birth_date' => $applicant->birth_date?->format('d/m/Y'),
            'address' => $applicant->address,
            'whatsapp' => $applicant->whatsapp_display,
            'email' => $applicant->email,
            'submitted_at' => $applicant->submitted_at?->translatedFormat('d F Y, H:i'),
            'photo_url' => $applicant->documents->contains('type', 'photo_4x6') ? route('status.photo') : null,
            'registration_status' => $applicant->registration_status,
            'payment_status' => $applicant->payment_status,
            'document_status' => $applicant->document_status,
            'selection_status' => $applicant->selection_status,
            'documents' => $applicant->documents,
            'payments' => $applicant->payments,
            'payment_url' => route('payment.show', $applicant->registration_number),
        ]]);
    }

    public function photo(Request $request): StreamedResponse
    {
        $id = $request->session()->get('status_applicant_id');
        abort_unless($id, 403);
        $applicant = Applicant::findOrFail($id);
        $photo = $applicant->documents()->where('type', 'photo_4x6')->latest('version')->firstOrFail();
        abort_unless($photo->disk === 'local' && Storage::disk('local')->exists($photo->path), 404);
        $disk = Storage::disk('local');

        return response()->stream(function () use ($disk, $photo): void {
            $stream = $disk->readStream($photo->path);
            abort_if($stream === false, 404);
            fpassthru($stream);
            fclose($stream);
        }, 200, [
            'Content-Type' => $photo->mime_type ?: 'image/jpeg',
            'Content-Length' => (string) $disk->size($photo->path),
            'Cache-Control' => 'private, max-age=300',
            'X-Content-Type-Options' => 'nosniff',
        ]);
    }
}
