<?php
namespace App\Jobs;
use App\Models\NotificationLog;use Illuminate\Bus\Queueable;use Illuminate\Contracts\Queue\ShouldQueue;use Illuminate\Foundation\Bus\Dispatchable;use Illuminate\Queue\{InteractsWithQueue,SerializesModels};use Illuminate\Support\Facades\{Http,Mail,URL};use Throwable;
class SendApplicantNotification implements ShouldQueue {use Dispatchable,InteractsWithQueue,Queueable,SerializesModels;public int $tries=3;public int $timeout=30;public function __construct(public int $logId,public string $message){}
public function handle():void{$log=NotificationLog::with('applicant')->findOrFail($this->logId);if($log->status==='sent')return;if(!$log->applicant){$log->update(['status'=>'skipped','last_error'=>'Data pendaftar sudah tidak tersedia.']);return;}$log->increment('attempts');try{if($log->channel==='email'){Mail::html($this->emailHtml($log),fn($mail)=>$mail->to($log->applicant->email)->subject($this->subject($log->event_type)));}else{$token=(string)config('services.fonnte.token');if($token===''){$log->update(['status'=>'skipped','last_error'=>'Fonnte belum dikonfigurasi.']);return;}$response=Http::withHeaders(['Authorization'=>$token])->asForm()->timeout(15)->post(rtrim(config('services.fonnte.base_url'),'/').'/send',['target'=>$log->applicant->whatsapp_normalized,'message'=>"*PMB PENDIDIKAN KADER ULAMA*\n\n{$this->message}\n\n_Cek status secara berkala melalui website resmi PMB PKU._",'countryCode'=>config('services.fonnte.country_code','62')])->throw();$log->provider_request_id=(string)($response->json('requestid')??'');}$log->update(['status'=>'sent','sent_at'=>now(),'last_error'=>null]);}catch(Throwable $e){$log->update(['status'=>'failed','last_error'=>str($e->getMessage())->limit(500)]);throw $e;}}
private function subject(string $event):string{return match(true){$event==='registration_created'=>'Pendaftaran PMB PKU Berhasil Diterima',str_starts_with($event,'payment_')=>'Pembaruan Pembayaran PMB PKU',str_starts_with($event,'document_')=>'Pembaruan Dokumen PMB PKU',str_starts_with($event,'selection_')=>'Pembaruan Hasil Seleksi PMB PKU',default=>'Informasi PMB Pendidikan Kader Ulama'};}
private function emailHtml(NotificationLog $log):string{$name=e($log->applicant->full_name);$number=e($log->applicant->registration_number);$message=nl2br(e($this->message));$statusUrl=e(URL::temporarySignedRoute('status.email',now()->addDays(90),['applicant'=>$log->applicant->id]));$year=now()->year;return <<<HTML
<!doctype html><html lang="id"><body style="margin:0;background:#f1f5f3;font-family:Arial,sans-serif;color:#17352c"><table width="100%" cellpadding="0" cellspacing="0" role="presentation"><tr><td style="padding:32px 16px"><table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="max-width:640px;margin:auto;background:#fff;border-radius:20px;overflow:hidden;box-shadow:0 12px 40px rgba(3,65,48,.10)"><tr><td style="padding:30px;background:#075a46;color:#fff"><div style="font-size:12px;letter-spacing:2px;text-transform:uppercase;color:#bce8d7">Pemberitahuan Resmi</div><h1 style="margin:8px 0 0;font-size:24px">PMB Pendidikan Kader Ulama</h1></td></tr><tr><td style="padding:30px"><p style="margin:0 0 18px;font-size:16px">Yth. <strong>{$name}</strong>,</p><div style="font-size:15px;line-height:1.75;color:#425b53">{$message}</div><div style="margin:24px 0;padding:16px;background:#f0f9f5;border-left:4px solid #d9ad2b;border-radius:10px"><div style="font-size:12px;color:#657a73;text-transform:uppercase;letter-spacing:1px">Nomor Pendaftaran</div><strong style="display:block;margin-top:5px;font-size:18px;color:#075a46">{$number}</strong></div><a href="{$statusUrl}" style="display:inline-block;padding:13px 22px;background:#08745a;color:#fff;text-decoration:none;border-radius:10px;font-weight:bold">Cek Status Pendaftaran</a><p style="margin:26px 0 0;font-size:13px;line-height:1.6;color:#73847e">Pesan ini dikirim otomatis oleh sistem PMB. Jangan membalas email ini. Jika membutuhkan bantuan, silakan hubungi panitia.</p></td></tr><tr><td style="padding:18px 30px;background:#043d31;color:#b9d3ca;font-size:12px;text-align:center">&copy; {$year} PMB Pendidikan Kader Ulama MUI Provinsi DKI Jakarta</td></tr></table></td></tr></table></body></html>
HTML;}
public function backoff():array{return [30,120,300];}}
